OPERATIONS = {
    "order.getProductOrderIds": {
        "method": "GET",
        "path": "/v1/pay-order/seller/orders/{orderId}/product-order-ids",
        "path_params": ["orderId"],
        "query": [],
        "body": [],
        "required": ["orderId"],
    },
    "order.getChangedOrders": {
        "method": "GET",
        "path": "/v1/pay-order/seller/product-orders/last-changed-statuses",
        "path_params": [],
        "query": [
            "lastChangedFrom",
            "lastChangedTo",
            "lastChangedType",
            "moreSequence",
            "limitCount",
        ],
        "body": [],
        "required": ["lastChangedFrom"],
    },
    "order.searchByCondition": {
        "method": "GET",
        "path": "/v1/pay-order/seller/product-orders",
        "path_params": [],
        "query": [
            "from",
            "to",
            "rangeType",
            "productOrderStatuses",
            "claimStatuses",
            "placeOrderStatusType",
            "fulfillment",
            "pageSize",
            "page",
            "quantityClaimCompatibility",
        ],
        "body": [],
        "required": ["from"],
    },
    "order.getDetails": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/query",
        "path_params": [],
        "query": [],
        "body": ["productOrderIds", "quantityClaimCompatibility"],
        "required": ["productOrderIds"],
    },
    "order.confirm": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/confirm",
        "path_params": [],
        "query": [],
        "body": ["productOrderIds"],
        "required": ["productOrderIds"],
    },
    "product.getOriginProduct": {
        "method": "GET",
        "path": "/v2/products/origin-products/{originProductNo}",
        "path_params": ["originProductNo"],
        "query": [],
        "body": [],
        "required": ["originProductNo"],
    },
    "product.getChannelProduct": {
        "method": "GET",
        "path": "/v2/products/channel-products/{channelProductNo}",
        "path_params": ["channelProductNo"],
        "query": [],
        "body": [],
        "required": ["channelProductNo"],
    },
    "delivery.dispatch": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/dispatch",
        "path_params": [],
        "query": [],
        "body": ["dispatchProductOrders"],
        "required": [
            "dispatchProductOrders",
            "dispatchProductOrders[].productOrderId",
            "dispatchProductOrders[].deliveryMethod",
            "dispatchProductOrders[].dispatchDate",
        ],
        "conditional_required": [
            {
                "path": "dispatchProductOrders[]",
                "when": {"field": "deliveryMethod", "equals": "DELIVERY"},
                "required": ["deliveryCompanyCode", "trackingNumber"],
            }
        ],
    },
    "delivery.delayDispatch": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/delay",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [
            "dispatchDueDate",
            "delayedDispatchReason",
            "dispatchDelayedDetailedReason",
        ],
        "required": [
            "productOrderId",
            "dispatchDueDate",
            "delayedDispatchReason",
        ],
    },
    "delivery.changeHopeDelivery": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/hope-delivery/change",
        "path_params": ["productOrderId"],
        "query": [],
        "body": ["hopeDeliveryYmd", "hopeDeliveryHm", "region", "changeReason"],
        "required": ["productOrderId", "hopeDeliveryYmd", "changeReason"],
    },
    "exchange.collectApprove": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/exchange/collect/approve",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [],
        "required": ["productOrderId"],
    },
    "exchange.redispatch": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/exchange/dispatch",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [
            "reDeliveryMethod",
            "reDeliveryCompany",
            "reDeliveryTrackingNumber",
        ],
        "required": [
            "productOrderId",
            "reDeliveryMethod",
        ],
        "conditional_required": [
            {
                "when": {"field": "reDeliveryMethod", "equals": "DELIVERY"},
                "required": ["reDeliveryCompany", "reDeliveryTrackingNumber"],
            }
        ],
    },
    "exchange.hold": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/exchange/holdback",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [
            "holdbackClassType",
            "holdbackExchangeDetailReason",
            "extraExchangeFeeAmount",
        ],
        "required": [
            "productOrderId",
            "holdbackClassType",
            "holdbackExchangeDetailReason",
        ],
    },
    "exchange.releaseHold": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/exchange/holdback/release",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [],
        "required": ["productOrderId"],
    },
    "exchange.reject": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/exchange/reject",
        "path_params": ["productOrderId"],
        "query": [],
        "body": ["rejectExchangeReason"],
        "required": ["productOrderId", "rejectExchangeReason"],
    },
    "return.request": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/return/request",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [
            "returnReason",
            "collectDeliveryMethod",
            "collectDeliveryCompany",
            "collectTrackingNumber",
            "returnQuantity",
        ],
        "required": ["productOrderId", "returnReason", "collectDeliveryMethod"],
    },
    "return.approve": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/return/approve",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [],
        "required": ["productOrderId"],
    },
    "return.hold": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/return/holdback",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [
            "holdbackClassType",
            "holdbackReturnDetailReason",
            "extraReturnFeeAmount",
        ],
        "required": [
            "productOrderId",
            "holdbackClassType",
            "holdbackReturnDetailReason",
        ],
    },
    "return.releaseHold": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/return/holdback/release",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [],
        "required": ["productOrderId"],
    },
    "return.reject": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/return/reject",
        "path_params": ["productOrderId"],
        "query": [],
        "body": ["rejectReturnReason"],
        "required": ["productOrderId", "rejectReturnReason"],
    },
    "cancel.request": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/cancel/request",
        "path_params": ["productOrderId"],
        "query": [],
        "body": ["cancelReason", "cancelDetailedReason", "cancelQuantity"],
        "required": ["productOrderId", "cancelReason"],
    },
    "cancel.approve": {
        "method": "POST",
        "path": "/v1/pay-order/seller/product-orders/{productOrderId}/claim/cancel/approve",
        "path_params": ["productOrderId"],
        "query": [],
        "body": [],
        "required": ["productOrderId"],
    },
}


def get_operation(operation):
    return OPERATIONS.get(operation)
